// This file is auto-generated by scripts/deploy.js after deployment.
// Manually fill in CONTRACT_ADDRESS and ABI if deploying outside the script.
const CONTRACT_ADDRESS = process.env.CONTRACT_ADDRESS || "";
const ABI = [
  "function issueCertificate(string memory _hash, string memory _recipient, string memory _issuer, string memory _eventName, string memory _date, string memory _ipfsUrl) public",
  "function verifyCertificate(string memory _hash) public view returns (string memory, string memory, string memory, string memory, string memory, string memory, bool)"
];

module.exports = { CONTRACT_ADDRESS, ABI };
