const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const CredLedger = await hre.ethers.getContractFactory("CredLedger");
  const contract = await CredLedger.deploy();
  await contract.waitForDeployment();

  const address = await contract.getAddress();
  console.log("CredLedger deployed to:", address);

  // Write ABI and address to backend config
  const artifact = await hre.artifacts.readArtifact("CredLedger");
  const configPath = path.join(__dirname, "../../backend/src/config/contract.js");

  const content = `// Auto-generated by deploy script
const CONTRACT_ADDRESS = "${address}";
const ABI = ${JSON.stringify(artifact.abi, null, 2)};
module.exports = { CONTRACT_ADDRESS, ABI };
`;
  fs.writeFileSync(configPath, content);
  console.log("Contract config written to backend/src/config/contract.js");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
